
const AllFUnders = [
  {
    _id: 1,
    project: " IITA",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: "Patrick Dunamis",
    email: "patoctave99@gmail.com",
    wallet: "Xngjrghrgdhrtujhg",
    country: "Nigeria",
    projectfounded: 10,
    status: "active",
  },
  {
    _id: 2,
    project: " IITA",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: "Patrick Dunamis",
    status: "active",
    email: "patoctave99@gmail.com",
    wallet: "Xngjrghrgdhrtujhg",
    country: "Nigeria",
    projectfounded: 10,
  },

  {
    _id: 3,
    project: " IITA",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: "Patrick Dunamis",
    status: "active",
    email: "patoctave99@gmail.com",
    wallet: "Xngjrghrgdhrtujhg",
    country: "Nigeria",
    projectfounded: 10,
  },

  {
    _id: 4,
    project: " IITA",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: "Patrick Dunamis",
    status: "active",
    email: "patoctave99@gmail.com",
    wallet: "Xngjrghrgdhrtujhg",
    country: "Nigeria",
    projectfounded: 10,
  },

  {
    _id: 5,
    project: " IITA",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: "Patrick Dunamis",
    status: "active",
    email: "patoctave99@gmail.com",
    wallet: "Xngjrghrgdhrtujhg",
    country: "Nigeria",
    projectfounded: 10,
  },

  {
    _id: 6,
    project: " IITA",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: "Patrick Dunamis",
    status: "active",
    email: "patoctave99@gmail.com",
    wallet: "Xngjrghrgdhrtujhg",
    country: "Nigeria",
    projectfounded: 10,
  },

  {
    _id: 7,
    project: " IITA",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: "Patrick Dunamis",
    status: "active",
    email: "patoctave99@gmail.com",
    wallet: "Xngjrghrgdhrtujhg",
    country: "Nigeria",
    projectfounded: 10,
  },

  {
    _id: 8,
    project: " IITA",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: "Patrick Dunamis",
    status: "active",
    email: "patoctave99@gmail.com",
    wallet: "Xngjrghrgdhrtujhg",
    country: "Nigeria",
    projectfounded: 10,
  },

  {
    _id: 9,
    project: " IITA",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: "Patrick Dunamis",
    status: "active",
    email: "patoctave99@gmail.com",
    wallet: "Xngjrghrgdhrtujhg",
    country: "Nigeria",
    projectfounded: 10,
  },

  {
    _id: 10,
    project: " IITA",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: "Patrick Dunamis",
    status: "active",
    email: "patoctave99@gmail.com",
    wallet: "Xngjrghrgdhrtujhg",
    country: "Nigeria",
    projectfounded: 10,
  },

  {
    _id: 11,
    project: " IITA",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: "Patrick Dunamis",
    status: "active",
    email: "patoctave99@gmail.com",
    wallet: "Xngjrghrgdhrtujhg",
    country: "Nigeria",
    projectfounded: 10,
  },

  {
    _id: 12,
    project: " IITA",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: "Patrick Dunamis",
    status: "active",
    email: "patoctave99@gmail.com",
    wallet: "Xngjrghrgdhrtujhg",
    country: "Nigeria",
    projectfounded: 10,
  },

  {
    _id: 21,
    project: " IITA",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: "Patrick Dunamis",
    status: "active",
    email: "patoctave99@gmail.com",
    wallet: "Xngjrghrgdhrtujhg",
    country: "Nigeria",
    projectfounded: 10,
  },

  {
    _id: 14,
    project: " IITA",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: "Patrick Dunamis",
    status: "active",
    email: "patoctave99@gmail.com",
    wallet: "Xngjrghrgdhrtujhg",
    country: "Nigeria",
    projectfounded: 10,
  },

  {
    _id: 15,
    project: " IITA",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: "Patrick Dunamis",
    status: "active",
    email: "patoctave99@gmail.com",
    wallet: "Xngjrghrgdhrtujhg",
    country: "Nigeria",
    projectfounded: 10,
  },

  {
    _id: 16,
    project: " IITA",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: "Patrick Dunamis",
    status: "active",
    email: "patoctave99@gmail.com",
    wallet: "Xngjrghrgdhrtujhg",
    country: "Nigeria",
    projectfounded: 10,
  },

  {
    _id: 17,
    project: " IITA",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: "Patrick Dunamis",
    status: "active",
    email: "patoctave99@gmail.com",
    wallet: "Xngjrghrgdhrtujhg",
    country: "Nigeria",
    projectfounded: 10,
  },

  {
    _id: 18,
    project: " IITA",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: "Patrick Dunamis",
    status: "active",
    email: "patoctave99@gmail.com",
    wallet: "Xngjrghrgdhrtujhg",
    country: "Nigeria",
    projectfounded: 10,
  },

  {
    _id: 19,
    project: " IITA",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: "Patrick Dunamis",
    status: "active",
    email: "patoctave99@gmail.com",
    wallet: "Xngjrghrgdhrtujhg",
    country: "Nigeria",
    projectfounded: 10,
  },

  {
    _id: 20,
    project: " IITA",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: "Patrick Dunamis",
    status: "active",
    email: "patoctave99@gmail.com",
    wallet: "Xngjrghrgdhrtujhg",
    country: "Nigeria",
    projectfounded: 10,
  },
];
export default AllFUnders;
