
const AllInvestments = [
  {
    _id: 1,
    project: " IITA",
    // logo: <Grass />,
    name: "Patrick",
    category: "Agriculture",
    price: "$10",
    return: "12%",
    maturity: "6 Months",
    timeleft: "24 days",
  },
  {
    _id: 2,
    project: " IITA",
    // logo: <Grass />,
    name: "Patrick",
    category: "Agriculture",
    price: "$10",
    return: "12%",
    maturity: "6 Months",
    timeleft: "24 days",
  },

  {
    _id: 3,
    project: " IITA",
    // logo: <Grass />,
    name: "Patrick",
    category: "Agriculture",
    price: "$10",
    return: "12%",
    maturity: "6 Months",
    timeleft: "24 days",
  },

  {
    _id: 4,
    project: " IITA",
    // logo: <Grass />,
    name: "Patrick",
    category: "Agriculture",
    price: "$10",
    return: "12%",
    maturity: "6 Months",
    timeleft: "24 days",
  },

  {
    _id: 5,
    project: " IITA",
    // logo: <Grass />,
    name: "Patrick",
    category: "Agriculture",
    price: "$10",
    return: "12%",
    maturity: "6 Months",
    timeleft: "24 days",
  },

  {
    _id: 6,
    project: " IITA",
    // logo: <Grass />,
    name: "Patrick",
    category: "Agriculture",
    price: "$10",
    return: "12%",
    maturity: "6 Months",
    timeleft: "24 days",
  },

  {
    _id: 7,
    project: " IITA",
    // logo: <Grass />,
    name: "Patrick",
    category: "Agriculture",
    price: "$10",
    return: "12%",
    maturity: "6 Months",
    timeleft: "24 days",
  },

  {
    _id: 8,
    project: " IITA",
    // logo: <Grass />,
    name: "Patrick",
    category: "Agriculture",
    price: "$10",
    return: "12%",
    maturity: "6 Months",
    timeleft: "24 days",
  },

  {
    _id: 9,
    project: " IITA",
    // logo: <Grass />,
    name: "Patrick",
    category: "Agriculture",
    price: "$10",
    return: "12%",
    maturity: "6 Months",
    timeleft: "24 days",
  },

  {
    _id: 10,
    project: " IITA",
    // logo: <Grass />,
    name: "Patrick",
    category: "Agriculture",
    price: "$10",
    return: "12%",
    maturity: "6 Months",
    timeleft: "24 days",
  },

  {
    _id: 11,
    project: " IITA",
    // logo: <Grass />,
    name: "Patrick",
    category: "Agriculture",
    price: "$10",
    return: "12%",
    maturity: "6 Months",
    timeleft: "24 days",
  },

  {
    _id: 12,
    project: " IITA",
    // logo: <Grass />,
    name: "Patrick",
    category: "Agriculture",
    price: "$10",
    return: "12%",
    maturity: "6 Months",
    timeleft: "24 days",
  },

  {
    _id: 21,
    project: " IITA",
    // logo: <Grass />,
    name: "Patrick",
    category: "Agriculture",
    price: "$10",
    return: "12%",
    maturity: "6 Months",
    timeleft: "24 days",
  },

  {
    _id: 14,
    project: " IITA",
    // logo: <Grass />,
    name: "Patrick",
    category: "Agriculture",
    price: "$10",
    return: "12%",
    maturity: "6 Months",
    timeleft: "24 days",
  },

  {
    _id: 15,
    project: " IITA",
    // logo: <Grass />,
    name: "Patrick",
    category: "Agriculture",
    price: "$10",
    return: "12%",
    maturity: "6 Months",
    timeleft: "24 days",
  },

  {
    _id: 16,
    project: " IITA",
    // logo: <Grass />,
    name: "Patrick",
    category: "Agriculture",
    price: "$10",
    return: "12%",
    maturity: "6 Months",
    timeleft: "24 days",
  },

  {
    _id: 17,
    project: " IITA",
    // logo: <Grass />,
    name: "Patrick",
    category: "Agriculture",
    price: "$10",
    return: "12%",
    maturity: "6 Months",
    timeleft: "24 days",
  },

  {
    _id: 18,
    project: " IITA",
    // logo: <Grass />,
    name: "Patrick",
    category: "Agriculture",
    price: "$10",
    return: "12%",
    maturity: "6 Months",
    timeleft: "24 days",
  },

  {
    _id: 19,
    project: " IITA",
    // logo: <Grass />,
    name: "Patrick",
    category: "Agriculture",
    price: "$10",
    return: "12%",
    maturity: "6 Months",
    timeleft: "24 days",
  },

  {
    _id: 20,
    project: " IITA",
    // logo: <Grass />,
    name: "Patrick",
    category: "Agriculture",
    price: "$10",
    return: "12%",
    maturity: "6 Months",
    timeleft: "24 days",
  },
];
export default AllInvestments;
