import { Person2TwoTone } from "@mui/icons-material";
import { Stack, Typography } from "@mui/material";

const AllProjects = [
  {
    _id: 1,
    project: " Eskimo inc.",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: 1800,
    status: "active",
  },
  {
    _id: 2,
    project: " Eskimo inc.",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: 1800,
    status: "active",
  },
  {
    _id: 3,
    project: " Eskimo inc.",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: 1800,
    status: "active",
  },
  {
    _id: 4,
    project: " Eskimo inc.",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: 1800,
    status: "active",
  },
  {
    _id: 5,
    project: " Eskimo inc.",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: 1800,
    status: "active",
  },
  {
    _id: 6,
    project: " Eskimo inc.",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: 1800,
    status: "active",
  },
  {
    _id: 7,
    project: " Eskimo inc.",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: 1800,
    status: "active",
  },
  {
    _id: 8,
    project: " Eskimo inc.",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: 1800,
    status: "active",
  },
  {
    _id: 9,
    project: " Eskimo inc.",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: 1800,
    status: "active",
  },
  {
    _id: 10,
    project: " Eskimo inc.",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: 1800,
    status: "active",
  },
  {
    _id: 11,
    project: " Eskimo inc.",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: 1800,
    status: "active",
  },
  {
    _id: 12,
    project: " Eskimo inc.",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: 1800,
    status: "active",
  },
  {
    _id: 21,
    project: " Eskimo inc.",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: 1800,
    status: "active",
  },
  {
    _id: 14,
    project: " Eskimo inc.",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: 1800,
    status: "active",
  },
  {
    _id: 15,
    project: " Eskimo inc.",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: 1800,
    status: "active",
  },
  {
    _id: 16,
    project: " Eskimo inc.",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: 1800,
    status: "active",
  },
  {
    _id: 17,
    project: " Eskimo inc.",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: 1800,
    status: "active",
  },
  {
    _id: 18,
    project: " Eskimo inc.",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: 1800,
    status: "active",
  },
  {
    _id: 19,
    project: " Eskimo inc.",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: 1800,
    status: "active",
  },
  {
    _id: 20,
    project: " Eskimo inc.",
    industry: "Real Estate",
    volumeforsale: "200,000 TORO",
    volumefunded: "200,000 TORO",
    funders: 1800,
    status: "active",
  },
];
export default AllProjects;
