import { Person2TwoTone } from "@mui/icons-material";
import { Stack, Typography } from "@mui/material";

const ProjectData = [
  {
    id: 1,
    Project: " IITA",
    Totalvolume: "20M USDT",
    Volume: "200,000 TORO",
    Volume: "200,000 TORO",
    VolumeSold: "16M USDT",
    Funder: "Patrick Dunamis",
    FunderVolume: "200,000 TORO",
    TransactionType: "Funding",
    Time: 2,
  },
  {
    id: 2,
    Project: "IITA",
    Totalvolume: "20M USDT",
    Volume: "200,000 TORO",
    VolumeSold: "16M USDT",
    Funder: "Patrick Dunamis",
    FunderVolume: "200,000 TORO",
    TransactionType: "Funding",
    Time: 2,
  },
  {
    id: 3,
    Project: "IITA",
    Totalvolume: "20M USDT",
    Volume: "200,000 TORO",
    VolumeSold: "16M USDT",
    Funder: "Patrick Dunamis",
    FunderVolume: "200,000 TORO",
    TransactionType: "Funding",
    Time: 2,
  },
  {
    id: 4,
    Project: "IITA",
    Totalvolume: "20M USDT",
    Volume: "200,000 TORO",
    VolumeSold: "16M USDT",
    Funder: "Patrick Dunamis",
    FunderVolume: "200,000 TORO",
    TransactionType: "Funding",
    Time: 2,
  },
  {
    id: 5,
    Project: "IITA",
    Totalvolume: "20M USDT",
    Volume: "200,000 TORO",
    VolumeSold: "16M USDT",
    Funder: "Patrick Dunamis",
    FunderVolume: "200,000 TORO",
    TransactionType: "Funding",
    Time: 2,
  },
  {
    id: 6,
    Project: "IITA",
    Totalvolume: "20M USDT",
    Volume: "200,000 TORO",
    VolumeSold: "16M USDT",
    Funder: "Patrick Dunamis",
    FunderVolume: "200,000 TORO",
    TransactionType: "Funding",
    Time: 2,
  },
  {
    id: 7,
    Project: "IITA",
    Totalvolume: "20M USDT",
    Volume: "200,000 TORO",
    VolumeSold: "16M USDT",
    Funder: "Patrick Dunamis",
    FunderVolume: "200,000 TORO",
    TransactionType: "Funding",
    Time: 2,
  },
  {
    id: 8,
    Project: "IITA",
    Totalvolume: "20M USDT",
    Volume: "200,000 TORO",
    VolumeSold: "16M USDT",
    Funder: "Patrick Dunamis",
    FunderVolume: "200,000 TORO",
    TransactionType: "Funding",
    Time: 2,
  },
  {
    id: 9,
    Project: "IITA",
    Totalvolume: "20M USDT",
    Volume: "200,000 TORO",
    VolumeSold: "16M USDT",
    Funder: "Patrick Dunamis",
    FunderVolume: "200,000 TORO",
    TransactionType: "Funding",
    Time: 2,
  },
  {
    id: 10,
    Project: "IITA",
    Totalvolume: "20M USDT",
    Volume: "200,000 TORO",
    VolumeSold: "16M USDT",
    Funder: "Patrick Dunamis",
    FunderVolume: "200,000 TORO",
    TransactionType: "Funding",
    Time: 2,
  },
];
export default ProjectData;
